#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bank")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertcard_detail(card_detail instance);
  partial void Updatecard_detail(card_detail instance);
  partial void Deletecard_detail(card_detail instance);
  partial void Inserttrnsc_tbl(trnsc_tbl instance);
  partial void Updatetrnsc_tbl(trnsc_tbl instance);
  partial void Deletetrnsc_tbl(trnsc_tbl instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bankConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<card_detail> card_details
	{
		get
		{
			return this.GetTable<card_detail>();
		}
	}
	
	public System.Data.Linq.Table<trnsc_tbl> trnsc_tbls
	{
		get
		{
			return this.GetTable<trnsc_tbl>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.card_detail")]
public partial class card_detail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _card_no;
	
	private string _card_type;
	
	private string _amount;
	
	private string _expiry;
	
	private string _pin;
	
	private string _card_holder;
	
	private string _cvv_no;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Oncard_noChanging(string value);
    partial void Oncard_noChanged();
    partial void Oncard_typeChanging(string value);
    partial void Oncard_typeChanged();
    partial void OnamountChanging(string value);
    partial void OnamountChanged();
    partial void OnexpiryChanging(string value);
    partial void OnexpiryChanged();
    partial void OnpinChanging(string value);
    partial void OnpinChanged();
    partial void Oncard_holderChanging(string value);
    partial void Oncard_holderChanged();
    partial void Oncvv_noChanging(string value);
    partial void Oncvv_noChanged();
    #endregion
	
	public card_detail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_no", DbType="VarChar(50)")]
	public string card_no
	{
		get
		{
			return this._card_no;
		}
		set
		{
			if ((this._card_no != value))
			{
				this.Oncard_noChanging(value);
				this.SendPropertyChanging();
				this._card_no = value;
				this.SendPropertyChanged("card_no");
				this.Oncard_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_type", DbType="VarChar(50)")]
	public string card_type
	{
		get
		{
			return this._card_type;
		}
		set
		{
			if ((this._card_type != value))
			{
				this.Oncard_typeChanging(value);
				this.SendPropertyChanging();
				this._card_type = value;
				this.SendPropertyChanged("card_type");
				this.Oncard_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="VarChar(50)")]
	public string amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiry", DbType="VarChar(50)")]
	public string expiry
	{
		get
		{
			return this._expiry;
		}
		set
		{
			if ((this._expiry != value))
			{
				this.OnexpiryChanging(value);
				this.SendPropertyChanging();
				this._expiry = value;
				this.SendPropertyChanged("expiry");
				this.OnexpiryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin", DbType="VarChar(50)")]
	public string pin
	{
		get
		{
			return this._pin;
		}
		set
		{
			if ((this._pin != value))
			{
				this.OnpinChanging(value);
				this.SendPropertyChanging();
				this._pin = value;
				this.SendPropertyChanged("pin");
				this.OnpinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_holder", DbType="VarChar(50)")]
	public string card_holder
	{
		get
		{
			return this._card_holder;
		}
		set
		{
			if ((this._card_holder != value))
			{
				this.Oncard_holderChanging(value);
				this.SendPropertyChanging();
				this._card_holder = value;
				this.SendPropertyChanged("card_holder");
				this.Oncard_holderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvv_no", DbType="VarChar(50)")]
	public string cvv_no
	{
		get
		{
			return this._cvv_no;
		}
		set
		{
			if ((this._cvv_no != value))
			{
				this.Oncvv_noChanging(value);
				this.SendPropertyChanging();
				this._cvv_no = value;
				this.SendPropertyChanged("cvv_no");
				this.Oncvv_noChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trnsc_tbl")]
public partial class trnsc_tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _txnid;
	
	private string _amount;
	
	private string _status;
	
	private string _cardnofrom;
	
	private string _cardnoto;
	
	private string _transaction_date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntxnidChanging(string value);
    partial void OntxnidChanged();
    partial void OnamountChanging(string value);
    partial void OnamountChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OncardnofromChanging(string value);
    partial void OncardnofromChanged();
    partial void OncardnotoChanging(string value);
    partial void OncardnotoChanged();
    partial void Ontransaction_dateChanging(string value);
    partial void Ontransaction_dateChanged();
    #endregion
	
	public trnsc_tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txnid", DbType="VarChar(50)")]
	public string txnid
	{
		get
		{
			return this._txnid;
		}
		set
		{
			if ((this._txnid != value))
			{
				this.OntxnidChanging(value);
				this.SendPropertyChanging();
				this._txnid = value;
				this.SendPropertyChanged("txnid");
				this.OntxnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="VarChar(50)")]
	public string amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(20)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardnofrom", DbType="VarChar(50)")]
	public string cardnofrom
	{
		get
		{
			return this._cardnofrom;
		}
		set
		{
			if ((this._cardnofrom != value))
			{
				this.OncardnofromChanging(value);
				this.SendPropertyChanging();
				this._cardnofrom = value;
				this.SendPropertyChanged("cardnofrom");
				this.OncardnofromChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardnoto", DbType="VarChar(50)")]
	public string cardnoto
	{
		get
		{
			return this._cardnoto;
		}
		set
		{
			if ((this._cardnoto != value))
			{
				this.OncardnotoChanging(value);
				this.SendPropertyChanging();
				this._cardnoto = value;
				this.SendPropertyChanged("cardnoto");
				this.OncardnotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_date", DbType="VarChar(50)")]
	public string transaction_date
	{
		get
		{
			return this._transaction_date;
		}
		set
		{
			if ((this._transaction_date != value))
			{
				this.Ontransaction_dateChanging(value);
				this.SendPropertyChanging();
				this._transaction_date = value;
				this.SendPropertyChanged("transaction_date");
				this.Ontransaction_dateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
