#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MovieTicket")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertContact_US(Contact_US instance);
  partial void UpdateContact_US(Contact_US instance);
  partial void DeleteContact_US(Contact_US instance);
  partial void InsertLgn_Tbl(Lgn_Tbl instance);
  partial void UpdateLgn_Tbl(Lgn_Tbl instance);
  partial void DeleteLgn_Tbl(Lgn_Tbl instance);
  partial void InsertTheatre_Tbl(Theatre_Tbl instance);
  partial void UpdateTheatre_Tbl(Theatre_Tbl instance);
  partial void DeleteTheatre_Tbl(Theatre_Tbl instance);
  partial void InsertUserCard_Tbl(UserCard_Tbl instance);
  partial void UpdateUserCard_Tbl(UserCard_Tbl instance);
  partial void DeleteUserCard_Tbl(UserCard_Tbl instance);
  partial void InsertRefund_Tbl(Refund_Tbl instance);
  partial void UpdateRefund_Tbl(Refund_Tbl instance);
  partial void DeleteRefund_Tbl(Refund_Tbl instance);
  partial void InsertWallet(Wallet instance);
  partial void UpdateWallet(Wallet instance);
  partial void DeleteWallet(Wallet instance);
  partial void InsertShow_Tbl(Show_Tbl instance);
  partial void UpdateShow_Tbl(Show_Tbl instance);
  partial void DeleteShow_Tbl(Show_Tbl instance);
  partial void InsertMovie_Tbl(Movie_Tbl instance);
  partial void UpdateMovie_Tbl(Movie_Tbl instance);
  partial void DeleteMovie_Tbl(Movie_Tbl instance);
  partial void InsertTransaction_Tbl(Transaction_Tbl instance);
  partial void UpdateTransaction_Tbl(Transaction_Tbl instance);
  partial void DeleteTransaction_Tbl(Transaction_Tbl instance);
  partial void InsertSeat_Tbl(Seat_Tbl instance);
  partial void UpdateSeat_Tbl(Seat_Tbl instance);
  partial void DeleteSeat_Tbl(Seat_Tbl instance);
  partial void InsertBook_Ticket(Book_Ticket instance);
  partial void UpdateBook_Ticket(Book_Ticket instance);
  partial void DeleteBook_Ticket(Book_Ticket instance);
  partial void InsertMovie_Rating(Movie_Rating instance);
  partial void UpdateMovie_Rating(Movie_Rating instance);
  partial void DeleteMovie_Rating(Movie_Rating instance);
  partial void InsertRating(Rating instance);
  partial void UpdateRating(Rating instance);
  partial void DeleteRating(Rating instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MovieTicketConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Contact_US> Contact_US
	{
		get
		{
			return this.GetTable<Contact_US>();
		}
	}
	
	public System.Data.Linq.Table<Lgn_Tbl> Lgn_Tbls
	{
		get
		{
			return this.GetTable<Lgn_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<Theatre_Tbl> Theatre_Tbls
	{
		get
		{
			return this.GetTable<Theatre_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<UserCard_Tbl> UserCard_Tbls
	{
		get
		{
			return this.GetTable<UserCard_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<Refund_Tbl> Refund_Tbls
	{
		get
		{
			return this.GetTable<Refund_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<Wallet> Wallets
	{
		get
		{
			return this.GetTable<Wallet>();
		}
	}
	
	public System.Data.Linq.Table<Show_Tbl> Show_Tbls
	{
		get
		{
			return this.GetTable<Show_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<Movie_Tbl> Movie_Tbls
	{
		get
		{
			return this.GetTable<Movie_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<Transaction_Tbl> Transaction_Tbls
	{
		get
		{
			return this.GetTable<Transaction_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<Seat_Tbl> Seat_Tbls
	{
		get
		{
			return this.GetTable<Seat_Tbl>();
		}
	}
	
	public System.Data.Linq.Table<Book_Ticket> Book_Tickets
	{
		get
		{
			return this.GetTable<Book_Ticket>();
		}
	}
	
	public System.Data.Linq.Table<Movie_Rating> Movie_Ratings
	{
		get
		{
			return this.GetTable<Movie_Rating>();
		}
	}
	
	public System.Data.Linq.Table<Rating> Ratings
	{
		get
		{
			return this.GetTable<Rating>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contact_US")]
public partial class Contact_US : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Req_ID;
	
	private string _Name;
	
	private string _Email;
	
	private string _PhoneNo;
	
	private string _Subject;
	
	private string _Message;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReq_IDChanging(int value);
    partial void OnReq_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    #endregion
	
	public Contact_US()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Req_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Req_ID
	{
		get
		{
			return this._Req_ID;
		}
		set
		{
			if ((this._Req_ID != value))
			{
				this.OnReq_IDChanging(value);
				this.SendPropertyChanging();
				this._Req_ID = value;
				this.SendPropertyChanged("Req_ID");
				this.OnReq_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(50)")]
	public string PhoneNo
	{
		get
		{
			return this._PhoneNo;
		}
		set
		{
			if ((this._PhoneNo != value))
			{
				this.OnPhoneNoChanging(value);
				this.SendPropertyChanging();
				this._PhoneNo = value;
				this.SendPropertyChanged("PhoneNo");
				this.OnPhoneNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="VarChar(100)")]
	public string Subject
	{
		get
		{
			return this._Subject;
		}
		set
		{
			if ((this._Subject != value))
			{
				this.OnSubjectChanging(value);
				this.SendPropertyChanging();
				this._Subject = value;
				this.SendPropertyChanged("Subject");
				this.OnSubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lgn_Tbl")]
public partial class Lgn_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _UserEmail;
	
	private string _Password;
	
	private string _Status;
	
	private string _UserType;
	
	private string _Name;
	
	private string _PhoneNo;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    #endregion
	
	public Lgn_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string UserEmail
	{
		get
		{
			return this._UserEmail;
		}
		set
		{
			if ((this._UserEmail != value))
			{
				this.OnUserEmailChanging(value);
				this.SendPropertyChanging();
				this._UserEmail = value;
				this.SendPropertyChanged("UserEmail");
				this.OnUserEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(50)")]
	public string UserType
	{
		get
		{
			return this._UserType;
		}
		set
		{
			if ((this._UserType != value))
			{
				this.OnUserTypeChanging(value);
				this.SendPropertyChanging();
				this._UserType = value;
				this.SendPropertyChanged("UserType");
				this.OnUserTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(50)")]
	public string PhoneNo
	{
		get
		{
			return this._PhoneNo;
		}
		set
		{
			if ((this._PhoneNo != value))
			{
				this.OnPhoneNoChanging(value);
				this.SendPropertyChanging();
				this._PhoneNo = value;
				this.SendPropertyChanged("PhoneNo");
				this.OnPhoneNoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Theatre_Tbl")]
public partial class Theatre_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ThatreID;
	
	private string _ThatreName;
	
	private string _Area;
	
	private string _Address;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnThatreIDChanging(int value);
    partial void OnThatreIDChanged();
    partial void OnThatreNameChanging(string value);
    partial void OnThatreNameChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
	
	public Theatre_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThatreID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ThatreID
	{
		get
		{
			return this._ThatreID;
		}
		set
		{
			if ((this._ThatreID != value))
			{
				this.OnThatreIDChanging(value);
				this.SendPropertyChanging();
				this._ThatreID = value;
				this.SendPropertyChanged("ThatreID");
				this.OnThatreIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThatreName", DbType="NChar(10)")]
	public string ThatreName
	{
		get
		{
			return this._ThatreName;
		}
		set
		{
			if ((this._ThatreName != value))
			{
				this.OnThatreNameChanging(value);
				this.SendPropertyChanging();
				this._ThatreName = value;
				this.SendPropertyChanged("ThatreName");
				this.OnThatreNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="NChar(10)")]
	public string Area
	{
		get
		{
			return this._Area;
		}
		set
		{
			if ((this._Area != value))
			{
				this.OnAreaChanging(value);
				this.SendPropertyChanging();
				this._Area = value;
				this.SendPropertyChanged("Area");
				this.OnAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NChar(10)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserCard_Tbl")]
public partial class UserCard_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Card_ID;
	
	private string _UserEmail;
	
	private string _CardNumber;
	
	private string _Amount;
	
	private string _Cvv;
	
	private string _Pin;
	
	private string _ExpiryDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCard_IDChanging(int value);
    partial void OnCard_IDChanged();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnCardNumberChanging(string value);
    partial void OnCardNumberChanged();
    partial void OnAmountChanging(string value);
    partial void OnAmountChanged();
    partial void OnCvvChanging(string value);
    partial void OnCvvChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnExpiryDateChanging(string value);
    partial void OnExpiryDateChanged();
    #endregion
	
	public UserCard_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Card_ID
	{
		get
		{
			return this._Card_ID;
		}
		set
		{
			if ((this._Card_ID != value))
			{
				this.OnCard_IDChanging(value);
				this.SendPropertyChanging();
				this._Card_ID = value;
				this.SendPropertyChanged("Card_ID");
				this.OnCard_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="VarChar(50)")]
	public string UserEmail
	{
		get
		{
			return this._UserEmail;
		}
		set
		{
			if ((this._UserEmail != value))
			{
				this.OnUserEmailChanging(value);
				this.SendPropertyChanging();
				this._UserEmail = value;
				this.SendPropertyChanged("UserEmail");
				this.OnUserEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNumber", DbType="NChar(10)")]
	public string CardNumber
	{
		get
		{
			return this._CardNumber;
		}
		set
		{
			if ((this._CardNumber != value))
			{
				this.OnCardNumberChanging(value);
				this.SendPropertyChanging();
				this._CardNumber = value;
				this.SendPropertyChanged("CardNumber");
				this.OnCardNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="NChar(10)")]
	public string Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cvv", DbType="NChar(10)")]
	public string Cvv
	{
		get
		{
			return this._Cvv;
		}
		set
		{
			if ((this._Cvv != value))
			{
				this.OnCvvChanging(value);
				this.SendPropertyChanging();
				this._Cvv = value;
				this.SendPropertyChanged("Cvv");
				this.OnCvvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="NChar(10)")]
	public string Pin
	{
		get
		{
			return this._Pin;
		}
		set
		{
			if ((this._Pin != value))
			{
				this.OnPinChanging(value);
				this.SendPropertyChanging();
				this._Pin = value;
				this.SendPropertyChanged("Pin");
				this.OnPinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryDate", DbType="NChar(10)")]
	public string ExpiryDate
	{
		get
		{
			return this._ExpiryDate;
		}
		set
		{
			if ((this._ExpiryDate != value))
			{
				this.OnExpiryDateChanging(value);
				this.SendPropertyChanging();
				this._ExpiryDate = value;
				this.SendPropertyChanged("ExpiryDate");
				this.OnExpiryDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Refund_Tbl")]
public partial class Refund_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _RefundID;
	
	private string _TransactionID;
	
	private System.Nullable<int> _RefundAmount;
	
	private string _Status;
	
	private string _RefundDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRefundIDChanging(int value);
    partial void OnRefundIDChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnRefundAmountChanging(System.Nullable<int> value);
    partial void OnRefundAmountChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnRefundDateChanging(string value);
    partial void OnRefundDateChanged();
    #endregion
	
	public Refund_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int RefundID
	{
		get
		{
			return this._RefundID;
		}
		set
		{
			if ((this._RefundID != value))
			{
				this.OnRefundIDChanging(value);
				this.SendPropertyChanging();
				this._RefundID = value;
				this.SendPropertyChanged("RefundID");
				this.OnRefundIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="VarChar(50)")]
	public string TransactionID
	{
		get
		{
			return this._TransactionID;
		}
		set
		{
			if ((this._TransactionID != value))
			{
				this.OnTransactionIDChanging(value);
				this.SendPropertyChanging();
				this._TransactionID = value;
				this.SendPropertyChanged("TransactionID");
				this.OnTransactionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundAmount", DbType="Int")]
	public System.Nullable<int> RefundAmount
	{
		get
		{
			return this._RefundAmount;
		}
		set
		{
			if ((this._RefundAmount != value))
			{
				this.OnRefundAmountChanging(value);
				this.SendPropertyChanging();
				this._RefundAmount = value;
				this.SendPropertyChanged("RefundAmount");
				this.OnRefundAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundDate", DbType="VarChar(50)")]
	public string RefundDate
	{
		get
		{
			return this._RefundDate;
		}
		set
		{
			if ((this._RefundDate != value))
			{
				this.OnRefundDateChanging(value);
				this.SendPropertyChanging();
				this._RefundDate = value;
				this.SendPropertyChanged("RefundDate");
				this.OnRefundDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wallet")]
public partial class Wallet : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _WalletID;
	
	private string _EmailID;
	
	private System.Nullable<int> _Amount;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWalletIDChanging(int value);
    partial void OnWalletIDChanged();
    partial void OnEmailIDChanging(string value);
    partial void OnEmailIDChanged();
    partial void OnAmountChanging(System.Nullable<int> value);
    partial void OnAmountChanged();
    #endregion
	
	public Wallet()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WalletID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int WalletID
	{
		get
		{
			return this._WalletID;
		}
		set
		{
			if ((this._WalletID != value))
			{
				this.OnWalletIDChanging(value);
				this.SendPropertyChanging();
				this._WalletID = value;
				this.SendPropertyChanged("WalletID");
				this.OnWalletIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailID", DbType="VarChar(50)")]
	public string EmailID
	{
		get
		{
			return this._EmailID;
		}
		set
		{
			if ((this._EmailID != value))
			{
				this.OnEmailIDChanging(value);
				this.SendPropertyChanging();
				this._EmailID = value;
				this.SendPropertyChanged("EmailID");
				this.OnEmailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
	public System.Nullable<int> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Show_Tbl")]
public partial class Show_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ShowID;
	
	private System.Nullable<int> _CureentMovie;
	
	private System.Nullable<int> _CurrentTheatre;
	
	private string _ShowTime;
	
	private System.Nullable<int> _RemainingSeats;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShowIDChanging(int value);
    partial void OnShowIDChanged();
    partial void OnCureentMovieChanging(System.Nullable<int> value);
    partial void OnCureentMovieChanged();
    partial void OnCurrentTheatreChanging(System.Nullable<int> value);
    partial void OnCurrentTheatreChanged();
    partial void OnShowTimeChanging(string value);
    partial void OnShowTimeChanged();
    partial void OnRemainingSeatsChanging(System.Nullable<int> value);
    partial void OnRemainingSeatsChanged();
    #endregion
	
	public Show_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ShowID
	{
		get
		{
			return this._ShowID;
		}
		set
		{
			if ((this._ShowID != value))
			{
				this.OnShowIDChanging(value);
				this.SendPropertyChanging();
				this._ShowID = value;
				this.SendPropertyChanged("ShowID");
				this.OnShowIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CureentMovie", DbType="Int")]
	public System.Nullable<int> CureentMovie
	{
		get
		{
			return this._CureentMovie;
		}
		set
		{
			if ((this._CureentMovie != value))
			{
				this.OnCureentMovieChanging(value);
				this.SendPropertyChanging();
				this._CureentMovie = value;
				this.SendPropertyChanged("CureentMovie");
				this.OnCureentMovieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentTheatre", DbType="Int")]
	public System.Nullable<int> CurrentTheatre
	{
		get
		{
			return this._CurrentTheatre;
		}
		set
		{
			if ((this._CurrentTheatre != value))
			{
				this.OnCurrentTheatreChanging(value);
				this.SendPropertyChanging();
				this._CurrentTheatre = value;
				this.SendPropertyChanged("CurrentTheatre");
				this.OnCurrentTheatreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime", DbType="VarChar(50)")]
	public string ShowTime
	{
		get
		{
			return this._ShowTime;
		}
		set
		{
			if ((this._ShowTime != value))
			{
				this.OnShowTimeChanging(value);
				this.SendPropertyChanging();
				this._ShowTime = value;
				this.SendPropertyChanged("ShowTime");
				this.OnShowTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainingSeats", DbType="Int")]
	public System.Nullable<int> RemainingSeats
	{
		get
		{
			return this._RemainingSeats;
		}
		set
		{
			if ((this._RemainingSeats != value))
			{
				this.OnRemainingSeatsChanging(value);
				this.SendPropertyChanging();
				this._RemainingSeats = value;
				this.SendPropertyChanged("RemainingSeats");
				this.OnRemainingSeatsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movie_Tbl")]
public partial class Movie_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MovieID;
	
	private string _MovieName;
	
	private string _Description;
	
	private string _Director;
	
	private string _Release_Date;
	
	private string _MovieImage;
	
	private string _Status;
	
	private string _MovieTrailer;
	
	private string _MovieTyp;
	
	private string _Cast;
	
	private string _Story;
	
	private System.Nullable<int> _Likes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMovieIDChanging(int value);
    partial void OnMovieIDChanged();
    partial void OnMovieNameChanging(string value);
    partial void OnMovieNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDirectorChanging(string value);
    partial void OnDirectorChanged();
    partial void OnRelease_DateChanging(string value);
    partial void OnRelease_DateChanged();
    partial void OnMovieImageChanging(string value);
    partial void OnMovieImageChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnMovieTrailerChanging(string value);
    partial void OnMovieTrailerChanged();
    partial void OnMovieTypChanging(string value);
    partial void OnMovieTypChanged();
    partial void OnCastChanging(string value);
    partial void OnCastChanged();
    partial void OnStoryChanging(string value);
    partial void OnStoryChanged();
    partial void OnLikesChanging(System.Nullable<int> value);
    partial void OnLikesChanged();
    #endregion
	
	public Movie_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MovieID
	{
		get
		{
			return this._MovieID;
		}
		set
		{
			if ((this._MovieID != value))
			{
				this.OnMovieIDChanging(value);
				this.SendPropertyChanging();
				this._MovieID = value;
				this.SendPropertyChanged("MovieID");
				this.OnMovieIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieName", DbType="VarChar(50)")]
	public string MovieName
	{
		get
		{
			return this._MovieName;
		}
		set
		{
			if ((this._MovieName != value))
			{
				this.OnMovieNameChanging(value);
				this.SendPropertyChanging();
				this._MovieName = value;
				this.SendPropertyChanged("MovieName");
				this.OnMovieNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="VarChar(50)")]
	public string Director
	{
		get
		{
			return this._Director;
		}
		set
		{
			if ((this._Director != value))
			{
				this.OnDirectorChanging(value);
				this.SendPropertyChanging();
				this._Director = value;
				this.SendPropertyChanged("Director");
				this.OnDirectorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Release_Date", DbType="VarChar(50)")]
	public string Release_Date
	{
		get
		{
			return this._Release_Date;
		}
		set
		{
			if ((this._Release_Date != value))
			{
				this.OnRelease_DateChanging(value);
				this.SendPropertyChanging();
				this._Release_Date = value;
				this.SendPropertyChanged("Release_Date");
				this.OnRelease_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieImage", DbType="VarChar(MAX)")]
	public string MovieImage
	{
		get
		{
			return this._MovieImage;
		}
		set
		{
			if ((this._MovieImage != value))
			{
				this.OnMovieImageChanging(value);
				this.SendPropertyChanging();
				this._MovieImage = value;
				this.SendPropertyChanged("MovieImage");
				this.OnMovieImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTrailer", DbType="VarChar(MAX)")]
	public string MovieTrailer
	{
		get
		{
			return this._MovieTrailer;
		}
		set
		{
			if ((this._MovieTrailer != value))
			{
				this.OnMovieTrailerChanging(value);
				this.SendPropertyChanging();
				this._MovieTrailer = value;
				this.SendPropertyChanged("MovieTrailer");
				this.OnMovieTrailerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTyp", DbType="VarChar(50)")]
	public string MovieTyp
	{
		get
		{
			return this._MovieTyp;
		}
		set
		{
			if ((this._MovieTyp != value))
			{
				this.OnMovieTypChanging(value);
				this.SendPropertyChanging();
				this._MovieTyp = value;
				this.SendPropertyChanged("MovieTyp");
				this.OnMovieTypChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cast", DbType="VarChar(MAX)")]
	public string Cast
	{
		get
		{
			return this._Cast;
		}
		set
		{
			if ((this._Cast != value))
			{
				this.OnCastChanging(value);
				this.SendPropertyChanging();
				this._Cast = value;
				this.SendPropertyChanged("Cast");
				this.OnCastChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Story", DbType="VarChar(MAX)")]
	public string Story
	{
		get
		{
			return this._Story;
		}
		set
		{
			if ((this._Story != value))
			{
				this.OnStoryChanging(value);
				this.SendPropertyChanging();
				this._Story = value;
				this.SendPropertyChanged("Story");
				this.OnStoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Likes", DbType="Int")]
	public System.Nullable<int> Likes
	{
		get
		{
			return this._Likes;
		}
		set
		{
			if ((this._Likes != value))
			{
				this.OnLikesChanging(value);
				this.SendPropertyChanging();
				this._Likes = value;
				this.SendPropertyChanged("Likes");
				this.OnLikesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transaction_Tbl")]
public partial class Transaction_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Txn_ID;
	
	private string _EmailID;
	
	private string _Amount;
	
	private string _Status;
	
	private string _TransactionID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTxn_IDChanging(int value);
    partial void OnTxn_IDChanged();
    partial void OnEmailIDChanging(string value);
    partial void OnEmailIDChanged();
    partial void OnAmountChanging(string value);
    partial void OnAmountChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    #endregion
	
	public Transaction_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Txn_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Txn_ID
	{
		get
		{
			return this._Txn_ID;
		}
		set
		{
			if ((this._Txn_ID != value))
			{
				this.OnTxn_IDChanging(value);
				this.SendPropertyChanging();
				this._Txn_ID = value;
				this.SendPropertyChanged("Txn_ID");
				this.OnTxn_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailID", DbType="VarChar(50)")]
	public string EmailID
	{
		get
		{
			return this._EmailID;
		}
		set
		{
			if ((this._EmailID != value))
			{
				this.OnEmailIDChanging(value);
				this.SendPropertyChanging();
				this._EmailID = value;
				this.SendPropertyChanged("EmailID");
				this.OnEmailIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="VarChar(50)")]
	public string Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="VarChar(50)")]
	public string TransactionID
	{
		get
		{
			return this._TransactionID;
		}
		set
		{
			if ((this._TransactionID != value))
			{
				this.OnTransactionIDChanging(value);
				this.SendPropertyChanging();
				this._TransactionID = value;
				this.SendPropertyChanged("TransactionID");
				this.OnTransactionIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seat_Tbl")]
public partial class Seat_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Booking_ID;
	
	private string _Seat_No;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBooking_IDChanging(string value);
    partial void OnBooking_IDChanged();
    partial void OnSeat_NoChanging(string value);
    partial void OnSeat_NoChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public Seat_Tbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking_ID", DbType="VarChar(50)")]
	public string Booking_ID
	{
		get
		{
			return this._Booking_ID;
		}
		set
		{
			if ((this._Booking_ID != value))
			{
				this.OnBooking_IDChanging(value);
				this.SendPropertyChanging();
				this._Booking_ID = value;
				this.SendPropertyChanged("Booking_ID");
				this.OnBooking_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seat_No", DbType="VarChar(50)")]
	public string Seat_No
	{
		get
		{
			return this._Seat_No;
		}
		set
		{
			if ((this._Seat_No != value))
			{
				this.OnSeat_NoChanging(value);
				this.SendPropertyChanging();
				this._Seat_No = value;
				this.SendPropertyChanged("Seat_No");
				this.OnSeat_NoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Book_Ticket")]
public partial class Book_Ticket : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Bookin_ID;
	
	private string _ShowID;
	
	private string _TransactionID;
	
	private string _UserEmail;
	
	private string _Booking_Date;
	
	private string _Movie_Date;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookin_IDChanging(int value);
    partial void OnBookin_IDChanged();
    partial void OnShowIDChanging(string value);
    partial void OnShowIDChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnBooking_DateChanging(string value);
    partial void OnBooking_DateChanged();
    partial void OnMovie_DateChanging(string value);
    partial void OnMovie_DateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public Book_Ticket()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bookin_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Bookin_ID
	{
		get
		{
			return this._Bookin_ID;
		}
		set
		{
			if ((this._Bookin_ID != value))
			{
				this.OnBookin_IDChanging(value);
				this.SendPropertyChanging();
				this._Bookin_ID = value;
				this.SendPropertyChanged("Bookin_ID");
				this.OnBookin_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowID", DbType="VarChar(MAX)")]
	public string ShowID
	{
		get
		{
			return this._ShowID;
		}
		set
		{
			if ((this._ShowID != value))
			{
				this.OnShowIDChanging(value);
				this.SendPropertyChanging();
				this._ShowID = value;
				this.SendPropertyChanged("ShowID");
				this.OnShowIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="VarChar(MAX)")]
	public string TransactionID
	{
		get
		{
			return this._TransactionID;
		}
		set
		{
			if ((this._TransactionID != value))
			{
				this.OnTransactionIDChanging(value);
				this.SendPropertyChanging();
				this._TransactionID = value;
				this.SendPropertyChanged("TransactionID");
				this.OnTransactionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="VarChar(MAX)")]
	public string UserEmail
	{
		get
		{
			return this._UserEmail;
		}
		set
		{
			if ((this._UserEmail != value))
			{
				this.OnUserEmailChanging(value);
				this.SendPropertyChanging();
				this._UserEmail = value;
				this.SendPropertyChanged("UserEmail");
				this.OnUserEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking_Date", DbType="VarChar(MAX)")]
	public string Booking_Date
	{
		get
		{
			return this._Booking_Date;
		}
		set
		{
			if ((this._Booking_Date != value))
			{
				this.OnBooking_DateChanging(value);
				this.SendPropertyChanging();
				this._Booking_Date = value;
				this.SendPropertyChanged("Booking_Date");
				this.OnBooking_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Date", DbType="VarChar(MAX)")]
	public string Movie_Date
	{
		get
		{
			return this._Movie_Date;
		}
		set
		{
			if ((this._Movie_Date != value))
			{
				this.OnMovie_DateChanging(value);
				this.SendPropertyChanging();
				this._Movie_Date = value;
				this.SendPropertyChanged("Movie_Date");
				this.OnMovie_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movie_Rating")]
public partial class Movie_Rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _MovieID;
	
	private string _UserEmail;
	
	private string _Rating;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMovieIDChanging(System.Nullable<int> value);
    partial void OnMovieIDChanged();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnRatingChanging(string value);
    partial void OnRatingChanged();
    #endregion
	
	public Movie_Rating()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieID", DbType="Int")]
	public System.Nullable<int> MovieID
	{
		get
		{
			return this._MovieID;
		}
		set
		{
			if ((this._MovieID != value))
			{
				this.OnMovieIDChanging(value);
				this.SendPropertyChanging();
				this._MovieID = value;
				this.SendPropertyChanged("MovieID");
				this.OnMovieIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="VarChar(50)")]
	public string UserEmail
	{
		get
		{
			return this._UserEmail;
		}
		set
		{
			if ((this._UserEmail != value))
			{
				this.OnUserEmailChanging(value);
				this.SendPropertyChanging();
				this._UserEmail = value;
				this.SendPropertyChanged("UserEmail");
				this.OnUserEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="VarChar(50)")]
	public string Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rating")]
public partial class Rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _MovieId;
	
	private System.Nullable<int> _Rating1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMovieIdChanging(System.Nullable<int> value);
    partial void OnMovieIdChanged();
    partial void OnRating1Changing(System.Nullable<int> value);
    partial void OnRating1Changed();
    #endregion
	
	public Rating()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieId", DbType="Int")]
	public System.Nullable<int> MovieId
	{
		get
		{
			return this._MovieId;
		}
		set
		{
			if ((this._MovieId != value))
			{
				this.OnMovieIdChanging(value);
				this.SendPropertyChanging();
				this._MovieId = value;
				this.SendPropertyChanged("MovieId");
				this.OnMovieIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Rating", Storage="_Rating1", DbType="Int")]
	public System.Nullable<int> Rating1
	{
		get
		{
			return this._Rating1;
		}
		set
		{
			if ((this._Rating1 != value))
			{
				this.OnRating1Changing(value);
				this.SendPropertyChanging();
				this._Rating1 = value;
				this.SendPropertyChanged("Rating1");
				this.OnRating1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
